[Component]
    Components = [
        { Name = "GLOBAL.Chasing Horses LLC.Vintage LLC.Infrastructure.Purchase Processing.Shipping Service.shippingservice", Application = "GLOBAL.Chasing Horses LLC.Vintage LLC.Hipster Store.Webstore;July 4th Sale;1.2.9.1"},
        { Name = "GLOBAL.Chasing Horses LLC.Vintage LLC.Infrastructure.Purchase Processing.Shipping Service.shippingservice", Application = "GLOBAL.Chasing Horses LLC.Vintage LLC.Hipster Store.Webstore;Labor Day Sale;1.2.10.0"}
    ]    
    Version = "1.2.2"
    ChartName = "chart/shippingservice"
    DockerRepo = "quay.io/hipsterstore/shippingservice"
    GitUrl = "https://github.com/ortelius/store-shippingservice"
    HelmChart = "GLOBAL.HelmChart"