[Component]
    Components = [
         { Name = "GLOBAL.SF Tech.Online Store Company.Purchase Processing.Shipping Service.shippingservice", Application = "GLOBAL.SF Tech.Online Store Company.Hipster Store.Dev.Hipster Store;Labor Day Sale;1_2_10_2"}
    ]    
    Version = "1.2.2"
    ChartName = "chart/shippingservice"
    DockerRepo = "quay.io/hipsterstore/shippingservice"
    GitUrl = "https://github.com/ortelius/store-shippingservice"
    CustomAction = "GLOBAL.HelmChart"
    