[Component]
    Name = "GLOBAL.Chasing Horses LLC.Vintage LLC.Hipster Store.shippingservice"
    Version = "1.2.2"
    ChartName = "chart/shippingservice"
    DockerRepo = "quay.io/hipsterstore/shippingservice"
    GitUrl = "https://github.com/ortelius/store-shippingservice"
    HelmChart = "GLOBAL.HelmChart"
    Applications = [
        "GLOBAL.Chasing Horses LLC.Vintage LLC.Hipster Store.Webstore;July 4th Sale;1.2.9.1"
    ]