Application = "GLOBAL.Stella Horses.Online Store Company.Hipster Store;July 4th Sale"
Application_Version = "1.2.9.1"
DeployEnv = "GLOBAL.ortelius.saas.aks-cluster"

Name = "GLOBAL.Stella Horses.Online Store Company.Purchase Processing.Shipping Service.shippingservice"
Variant = "${BRANCH_NAME}"
Version = "v1.2.2.${BUILDNUM}-g${SHORT_SHA}"

[Export]
     IMAGE_TAG = "${Variant}-${Version}"

[Attributes]
     BuildId = "${BUILD_ID}"
     BuildUrl = "https://console.cloud.google.com/cloud-build/builds/${BUILD_ID}?project=${PROJECT_ID}"
     Chart = "chart/shippingservice"
     ChartNameSpace = "stores"
     CustomAction = "GLOBAL.HelmChart"
     DockerBuildDate = "${BLDDATE}"
     DockerRepo = "quay.io/hipsterstore/shippingservice"
     DockerSha = "${DIGEST}"
     DockerTag = "${IMAGE_TAG}"
     GitBranch = "${BRANCH_NAME}"
     GitCommit = "${SHORT_SHA}"
     GitRepo = "${GIT_REPO}"
     GitTag = "${TAG_NAME}"
     GitUrl = "${GIT_URL}"
     License = "/workspace/LICENSE.md"
     Readme = "/workspace/README.md"
     ServiceOwner = "GLOBAL.Santa Fe Software.ETaylor"
