apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ include "shipppingservice.name" . }}
spec:
  selector:
    matchLabels:
      app:  {{ include "shipppingservice.name" . }}
  template:
    metadata:
      labels:
        app:  {{ include "shipppingservice.name" . }}
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: {{ include "shipppingservice.name" . }}
          image: "{{ .Values.DockerRepo }}:{{ .Values.DockerTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }} 
          ports:
          - containerPort: 50051
          env:
          - name: PORT
            value: "50051"
          readinessProbe:
            periodSeconds: 5
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50051"]
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50051"]
  #        env:
  #          - name: JAEGER_SERVICE_ADDR
  #            value: "jaeger-collector:14268"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi